return {
  "Abraham Moss",
  "Altrincham",
  "Anchorage",
  "Ashton Moss",
  "Ashton-under-Lyne",
  "Ashton West",
  "Audenshaw",
  "Baguley",
  "Barlow Moor Road",
  "Barton Dock Road",
  "Benchill",
  "Besses o'th' Barn",
  "Bowker Vale",
  "Broadway",
  "Brooklands",
  "Burton Road",
  "Bury",
  "Cemetery Road",
  "Central Park",
  "Chorlton",
  "Clayton Hall",
  "Cornbrook",
  "Crossacres",
  "Crumpsall",
  "Dane Road",
  "Deansgate-Castlefield",
  "Derker",
  "Didsbury Village",
  "Droylsden",
  "East Didsbury",
  "Eccles",
  "Edge Lane",
  "Etihad Campus",
  "Exchange Quay",
  "Exchange Square",
  "Failsworth",
  "Firswood",
  "Freehold",
  "Harbour City",
  "Heaton Park",
  "Hollinwood",
  "Holt Town",
  "Imperial War Museum",
  "Kingsway Business Park",
  "Ladywell",
  "Langworthy",
  "Manchester Airport",
  "Market Street",
  "Martinscroft",
  "MediaCityUK",
  "Milnrow",
  "Monsall",
  "Moor Road",
  "Navigation Road",
  "New Islington",
  "Newbold",
  "Newhey",
  "N'ton Heath Moston",
  "Northern Moor",
  "Old Trafford",
  "Oldham Central",
  "Oldham King Street",
  "Oldham Mumps",
  "Parkway",
  "Peel Hall",
  "Piccadilly",
  "Piccadilly Gardens",
  "Pomona",
  "Prestwich",
  "Queens Road",
  "Radcliffe",
  "Robinswood Road",
  "Rochdale Station",
  "Rochdale Centre",
  "Roundthorn",
  "Sale",
  "Sale Water Park",
  "Salford Quays",
  "Shadowmoss",
  "Shaw & Crompton",
  "Shudehill",
  "South Chadderton",
  "St Peter's Square",
  "St Werburgh's Road",
  "Stretford",
  "The Trafford Centre",
  "Timperley",
  "Trafford Bar",
  "Velopark",
  "Victoria",
  "Village",
  "Weaste",
  "West Didsbury",
  "Westwood",
  "Wharfside",
  "Whitefield",
  "Withington",
  "Wythenshawe Park",
  "Wythenshawe Town"
}